### ISSUE TITLE
Can't use string columns in pandas dataset

### ISSUE THREAD

**Issue by sammosummo** [mwshinn/PyDDM#31]
Unsure whether this is intended, a bug, of too much of an edge case but a pandas `DataFrame` cannot be turned into a `Sample` if it contains string columns.

```python
import pandas as pd
from ddm import Sample


df = pd.DataFrame([
    {"cond": -0.5, "rt": 1.1, "response": 0},
    {"cond": 0., "rt": 2.1, "response": 1},
    {"cond": 0.1, "rt": 1.2, "response": 1},
])
df["extra_col"] = 1
Sample.from_pandas_dataframe(
    df, rt_column_name="rt", correct_column_name="response"
)  # works
df["extra_col"] = "hello"
Sample.from_pandas_dataframe(
    df, rt_column_name="rt", correct_column_name="response"
)  # doesn't work
```
Produces the error:
```python
AttributeError: 'str' object has no attribute 'rint'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/samuelrobertmathias/miniconda3/envs/psychoacoustics/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 58, in _wrapfunc
    return bound(*args, **kwds)
TypeError: loop of ufunc does not support argument 0 of type str which has no callable rint method

During handling of the above exception, another exception occurred:

AttributeError: 'str' object has no attribute 'rint'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/samuelrobertmathias/PycharmProjects/FrequencyRT/_explore_rts.py", line 17, in <module>
    Sample.from_pandas_dataframe(
  File "/Users/samuelrobertmathias/miniconda3/envs/psychoacoustics/lib/python3.8/site-packages/paranoid/decorators.py", line 126, in _decorated
    returnvalue = func(*args, **kwargs)
  File "/Users/samuelrobertmathias/miniconda3/envs/psychoacoustics/lib/python3.8/site-packages/ddm/sample.py", line 212, in from_pandas_dataframe
    conditions = {k: (pt(df[c][k]), pt(df[nc][k]), np.asarray([])) for k in column_names}
  File "/Users/samuelrobertmathias/miniconda3/envs/psychoacoustics/lib/python3.8/site-packages/ddm/sample.py", line 212, in <dictcomp>
    conditions = {k: (pt(df[c][k]), pt(df[nc][k]), np.asarray([])) for k in column_names}
  File "/Users/samuelrobertmathias/miniconda3/envs/psychoacoustics/lib/python3.8/site-packages/ddm/sample.py", line 207, in pt
    if np.all(arr == np.round(arr)):
  File "<__array_function__ internals>", line 5, in round_
  File "/Users/samuelrobertmathias/miniconda3/envs/psychoacoustics/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 3637, in round_
    return around(a, decimals=decimals, out=out)
  File "<__array_function__ internals>", line 5, in around
  File "/Users/samuelrobertmathias/miniconda3/envs/psychoacoustics/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 3262, in around
    return _wrapfunc(a, 'round', decimals=decimals, out=out)
  File "/Users/samuelrobertmathias/miniconda3/envs/psychoacoustics/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 67, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "/Users/samuelrobertmathias/miniconda3/envs/psychoacoustics/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 44, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
TypeError: loop of ufunc does not support argument 0 of type str which has no callable rint method
```

**Comment by mwshinn** [comment]
Yes, this is by design, conditions cannot be strings.  Do you have a use case for strings as conditions?  They are already partially implemented but not maintained/tested and thus disabled.   Either way, documentation could be improved.

**Comment by sammosummo** [comment]
> Do you have a use case for strings as conditions?

Any situation where conditions are categories. The most obvious circumstance is when you have multiple subjects in the same data frame identified by their subject ID in a column, and one wants to fit some but not all DDM parameters separately per person.

It’s not a big deal, because one could dummy code categories with a design matrix created via patsy for instance and append it to the data frame.

Perhaps an explicit `NoStringColumnsInDataFrameError` or something would help to make it clear that this isn’t a bug.
